<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-25T08:12:36Z" name="Default suite" finished-at="2021-01-25T08:13:11Z" duration-ms="35409">
    <groups>
    </groups>
    <test started-at="2021-01-25T08:12:36Z" name="Default test" finished-at="2021-01-25T08:13:11Z" duration-ms="35409">
      <class name="TestCaseCreation.LoginPageFunctionality">
        <test-method is-config="true" signature="SetExtent()[pri:0, instance:TestCaseCreation.LoginPageFunctionality@4b7dc788]" started-at="2021-01-25T13:42:36Z" name="SetExtent" finished-at="2021-01-25T13:42:36Z" duration-ms="528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetExtent -->
        <test-method is-config="true" signature="HomePageNavigation()[pri:0, instance:TestCaseCreation.LoginPageFunctionality@4b7dc788]" started-at="2021-01-25T13:42:36Z" name="HomePageNavigation" finished-at="2021-01-25T13:42:53Z" duration-ms="17102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePageNavigation -->
        <test-method signature="VerifyTitle()[pri:1, instance:TestCaseCreation.LoginPageFunctionality@4b7dc788]" started-at="2021-01-25T13:42:53Z" name="VerifyTitle" finished-at="2021-01-25T13:43:03Z" duration-ms="10067" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [eCommerce demo store] but found [Welcome to CK-12 Foundation | CK-12 Foundation]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [eCommerce demo store] but found [Welcome to CK-12 Foundation | CK-12 Foundation]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at TestCaseCreation.LoginPageFunctionality.VerifyTitle(LoginPageFunctionality.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTitle -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCaseCreation.LoginPageFunctionality@4b7dc788]" started-at="2021-01-25T13:43:03Z" name="tearDown" finished-at="2021-01-25T13:43:10Z" duration-ms="6197" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyTitle status=FAILURE method=LoginPageFunctionality.VerifyTitle()[pri:1, instance:TestCaseCreation.LoginPageFunctionality@4b7dc788] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:TestCaseCreation.LoginPageFunctionality@4b7dc788]" started-at="2021-01-25T13:43:10Z" name="endReport" finished-at="2021-01-25T13:43:11Z" duration-ms="1475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- TestCaseCreation.LoginPageFunctionality -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
